spring:
  datasource:
    url: jdbc:mysql://152.67.218.230:3306/testdb?serverTimezone=Asia/Seoul
    username: root
    password: test1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.springframework.security: TRACE

jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token:
    access-expiration: 3600000    # 1시간
    refresh-expiration: 1209600000 # 2주
api:
  key: YpYSmykXUtWhZkDrVkHdPOnT0VusIHP5LNwOb1WN87NfKD0y8BC
  count: 110 #한 번 호출시 가지고 올 데이터 양

#메일 설정
mail:
  chat-url: http://localhost:3000/chat/
  host: smtp.gmail.com
  port: 587
  username: dongokim99@gmail.com
  password: fhct bwcz ysxs pamv
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
  templates:
    path: mail-templates/
    recruitment-chat: recruitment-chat-template

    #15분 - 2300개